graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true
  pageTitle: GraphiQL

spring:
  application:
    name: news-service

  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-plarform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      default-schema: news_service

  datasource:
    platform: ${datasource.platform}
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driverClassName: org.postgresql.Driver

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.url}